### PR TITLE
Fix unreachable code in GenericComponentPass.cs

### PR DESCRIPTION
**Pull request by rolshevsky**

### CODE REVIEW

**Comment by Andrzej-W** [comment]
Nice. Is it from JetBrains Rider or your own brain? 😄

**Comment by Gaulomatic** [comment]
Rider is great :-)

**Comment by danroth27** [comment]
Thanks @rolshevsky! Would you be willing to also add some tests that cover these cases?

**Comment by SteveSandersonMS** [comment]
@rolshevsky I was about to migrate this PR over to https://github.com/aspnet/aspnetcore but I see you've closed it. Do you feel this PR is no longer applicable for some reason? Or were you going to create your own new PR at https://github.com/aspnet/aspnetcore?

**Pull request closed without merging**
