### PR TITLE
Support the full range of all basic types. Deserialize byte[] from base64.

### PR DESCRIPTION
**Pull request by ericwj**

### CODE REVIEW

**Comment by ericwj** [comment]
#966

**Comment by SteveSandersonMS** [comment]
Thanks @ericwj for contributing this! I appreciate that you've been thorough with this PR.

I wasn't expecting it to involve such extensive code changes. In #966, you mentioned:

> The first needs a single line changed, the second needs 2 added lines, the third needs two if else statements added.

Since we are specifically *not* trying to build and maintain an all-encompassing JSON library inside Blazor, we'd generally favour not adding or changing complex behaviour. Rather, if a change this sophisticated is needed, it would be better to publish it as a separate package that developers can use if they need.

Would you be interested in publishing your own fork of the JSON utils as a separate package?

Or is there any way you can reduce the scope of the changes just to the few very small tweaks originally mentioned in #966? If it really was just a couple of tiny changes we'd be happy to merge it. Of course, I understand that would mean covering a smaller range of functionality, which is explicitly our goal for the built-in JSON util which will be removed at some point anyway when superseded.

**Comment by Suchiman** [comment]
If it's going to be removed anyway, whats the problem with reducing friction in the mean time?

**Comment by SteveSandersonMS** [comment]
@Suchiman Just that it's taking away time from the real project goals. Every change to the JSON code involves careful review and may introduce new issues. We think we can provide better value to the community by focusing elsewhere.

@ericwj How would you feel about publishing a separate JSON util package? We'd definitely point people to it whenever they have more sophisticated requirements than the built-in package handles. If the community is keen to develop this further it would be great to decouple it.

**Comment by Andrzej-W** [comment]
Decimal data type is crucial in any LOB application. I understand that Blazor is an experimental framework now and we will see a lot of changes in the future. Some of us want to test Blazor in real word scenarios and it is inconvenient when we don't have full support for basic data types. Please merge this commit.

**Comment by ericwj** [comment]
I would probably revert this to the three lines. Maybe I can make the promised two if statements (the changes to ParseNumber) somewhat simpler either by just trying decimal or ulong first and falling back to long/double if success is false. That would (further) reduce performance because it would change the default type returned for all floating point numbers to decimal.

**Comment by SteveSandersonMS** [comment]
@ericwj If that's your preference, that sounds OK.

Personally, I suspect it might be time for a community-led JSON package, presumably based on a fork of the SimpleJson code in this repo. If there are places where Blazor's API makes it hard or impossible to use an external JSON serializer, we would prioritise extending the APIs to make that easier. This work is needed in the long term anyway, since using third-party JSON libraries will always be a scenario.

**Comment by ericwj** [comment]
Most people will default to getting Json.NET and find that it crashes however simple an object you try to deserialize.

Currently its probably the runtime that has some quirks causing this - if it weren't the case I wouldn't consider making these changes but use Json.NET (although its big and complex).

Besides that - if this isn't supposed to be consumed in the default case, then it shouldn't surface through the extensions methods on HttpClient or in any other place by default. It'd probably have to be internal.

But, just as ASP.NET includes Json.NET, it'd be my preference if Blazor would have something so basic inbox.

**Comment by ericwj** [comment]
Its probably easiest to create a new pull request @SteveSandersonMS?

Would you like to have a [look at it](https://github.com/ericwj/Blazor/compare/feature/simplejson-min?expand=1) before I submit it?

If this isn't simple enough, the alternative of literally three lines will only add support for sbyte, ushort, uint and ulong but fail for any integers outside the range of long (half the range of ulong will be supported) and loose precision if the 54 bits of double aren't enough.

**Comment by Daddoon** [comment]
Hello @ericwj,

For Json.net you may take a look and some test at my fork if you find it usefull:

[Json.NET.Aot](https://github.com/Daddoon/Json.NET.Aot)

It's based on SaladLab Json.Net 9.0.1 Aot compatibility library, initially for Unity3D, but this version is upgraded to .Net standard 2.0. I use it on UWP/Android/iOS (Xamarin) and Blazor.

**Comment by SteveSandersonMS** [comment]
@owaits You can use a more powerful JSON library such as Json.NET. Just note that you need to configure the linker not to strip out `System.Linq.Expressions*` ([see docs](https://github.com/aspnet/Blazor.Docs/blob/master/docs/host-and-deploy/configure-linker.md)). This is a temporary issue that should be resolved in Blazor 0.7.0.

Longer term, we intend to swap out the default JSON library with a more powerful one.

**Comment by danroth27** [comment]
At this point we think we'd like to take a different approach with the implementation. We're investigating using a different JSON implementation, so we'd prefer not to take more involved changes to the existing SimpleJson code base.  As such, I'm closing this issue.

**Comment by Suchiman** [comment]
@danroth27 btw. is this expected to be the new JSON API comming to .NET Core 3?

**Comment by danroth27** [comment]
That's the hope: https://github.com/dotnet/announcements/issues/90

**Pull request closed without merging**
