### PR TITLE
minify blazor.js

### PR DESCRIPTION
**Pull request by reaction1989**
#1003

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks for this contribution, @reaction1989!

To make this change, we'd need a few further enhancements:

 * Only minify in "release" mode builds (i.e., in MSBuild, using the condition `Condition="'$(Configuration)' == 'Release'"`)
 * Clean up the changes to indentation so as to preserve the existing conventions and not add the redundant `<Folder Include="dist\" />`.
 * Make the application actually load the `.min.js` file when running in the production environment. Currently even though `blazor.min.js` is generated in this PR, it never gets used at runtime.
 * Fix whatever this has broken in the AppVeyor/Travis builds

Please let us know whether you'd be interested in adding these enhancements. Thanks!

**Comment by reaction1989** [comment]
I will have a Look at it 😊

Am 25.06.2018 um 13:06 schrieb Steve Sanderson <notifications@github.com<mailto:notifications@github.com>>:


Thanks for this contribution, @reaction1989<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Freaction1989&data=02%7C01%7C%7C3d74779b2dac48897a1a08d5da8bb116%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636655215854210967&sdata=Z2MDHikjppB7GJF94FRZ%2FgHx%2FvJk0CvsZggGiN0zXfw%3D&reserved=0>!

To make this change, we'd need a few further enhancements:

  *   Only minify in "release" mode builds (i.e., in MSBuild, using the condition Condition="'$(Configuration)' == 'Release'")
  *   Clean up the changes to indentation so as to preserve the existing conventions and not add the redundant <Folder Include="dist\" />.
  *   Make the application actually load the .min.js file when running in the production environment. Currently even though blazor.min.js is generated in this PR, it never gets used at runtime.
  *   Fix whatever this has broken in the AppVeyor/Travis builds

Please let us know whether you'd be interested in adding these enhancements. Thanks!

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know. Please rebase your changes onto `dev` before starting, because we've changed some bits of the JS project build process that will affect this PR (we've upgraded to Webpack v4).

**Comment by SteveSandersonMS** [comment]
Since this has been pending for a while, we're going to do this in a simpler way in #1090, so I'll close this one.

@reaction1989, hope that's OK with you! If not please let us know and we can figure out how to use this PR.

**Pull request closed without merging**
