### PR TITLE
Fix razor compilation error for mixed event handler content (#1530)

### LINKED ISSUE #1530: An error while parsing .cshtml
I have a line in Teachers.cshtml:
`<button onclick="window.location.href = '/teacher/@(teacher.Id)/';">More info...</button>`
After complation I have the following line in Teachers.g.cs (/obj/Debug/netstandart2.0/Pages/):
`builder.AddAttribute(24, "onclick", (Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>() + "window.location.href" + " =" + " \'/teacher/" + (teacher.Id) + "/\';" + ()));`
And an error message:

> CS1525	Invalid expression term ")"

### PR DESCRIPTION
**Pull request by BickelLukas**
If a event Handler contained a mixture of c# and html content the compilation failed. Now it compiles down to a c# template string. 

`<button onclick="alert(@(a)b)">...</button>`
turns into 
`$"alert({a}b)"`

I also renamed the other test I created in my last PR for consistency.

fixes #1530

### CODE REVIEW

**Comment by BickelLukas** [comment]
@adrian109 Here's the fix I promised in #1577

**Comment by BickelLukas** [comment]
@SteveSandersonMS Any update or feedback on this?

**Comment by danroth27** [comment]
We should talk a bit more about this scenario before taking any action. We're concerned about the potential for XSS issues if we enable this scenario.

**Comment by BickelLukas** [comment]
@danroth27 What do you think we should do to combat this issue?

**Comment by danroth27** [comment]
@BickelLukas We might completely disallow using C# expressions in event handler attributes unless you specifically signal that you know you are rendering some raw JavaScript.

**Comment by BickelLukas** [comment]
@danroth27 Do you have a proposal on how users might me able to do that?

**Comment by danroth27** [comment]
@BickelLukas We might need a new primitive similar to how we support rendering raw HTML in components today: https://blazor.net/docs/components/index.html#raw-html

**Comment by SteveSandersonMS** [comment]
For now I'm going to close this, because as-is this would introduce XSS vulnerabilities. If @BickelLukas or anyone else would like to propose a newer version that addresses the XSS concern by using `MarkupString` or similar, it can be posted to https://github.com/aspnet/aspnetcore. Hope that's OK!

**Pull request closed without merging**
