### PR TITLE
Fix right mouse click on <a href""> in firefox

### PR DESCRIPTION
**Pull request by reaction1989**
#982

### CODE REVIEW

**Comment by Suchiman** [comment]
Should this perhaps use [button](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button) instead of [which](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which) which appears to be non standard?

**Comment by Andrzej-W** [comment]
@reaction1989 In all web browsers I have tested middle click (mouse wheel click) opens link in a new tab. Unfortunately in Blazor middle click on internal link works exactly the same as left click. I think that your small change will fix this problem also. Thanks!

**Comment by SteveSandersonMS** [comment]
Thanks, @reaction1989 and @Suchiman! This is now merged.

**Comment by RemiBou** [comment]
maybe we could've updated eventHasSpecialKey with the new check "|| event.bouton === 0"

**Comment by RemiBou** [comment]
eventHasSpecialKey is here for handling those cases when we don't want to override the browser behavior (ctrl click, shift click). The check button === 0 could be in this method as it's the same goal. Is that clear enough ?

**Comment by Andrzej-W** [comment]
In my humble opinion eventHasSpecialKey is a utility function. Similarly isWithinBaseUriSpace is also utility function. Both functions together + outer `if` are used to decide if we want to perform internal navigation or not.

**Comment by RemiBou** [comment]
fair enough

**Pull request merged**
