### PR TITLE
Rebrand to -rc1

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by Pilchie** [comment]
Given client side blazor is not going to production with 3.0, is this the branding we want?  @danroth27

**Comment by mmitche** [comment]
@Pilchie Is the intent to leave the 3.0 release bits banded as preview9?

**Comment by Pilchie** [comment]
I'm not currently proposing an alternative, just pointing out that we need to make a decision.

**Comment by dougbu** [comment]
@rynowak where's that issue you filed about holding back the versions of client-side Blazor packages from this repo and AspNetCore? Should we move this repo to `preview10` and will that sort correctly?

(Holding client-side packages back is to do here but will require a few special cases in AspNetCore)

**Comment by mmitche** [comment]
@dougbu I don't think we can move to preview10, as it sorts lower in precedence than preview9

**Comment by danroth27** [comment]
No, we don't want rc1 branding for Blazor WebAssembly. Blazor WebAssembly is still in preview. Can we leave the Blazor WebAssembly packages as preview9, but with a newer build number for the 3.0 release? Once we ship the first preview of 3.1 we will want the Blazor WebAssembly branding to align with that. I think of the first Blazor WebAssembly release as part of 3.1 that ships a bit later.

**Comment by dougbu** [comment]
> with a newer build number for the 3.0 release? 

Well, that part happens automatically. Can just close this issue then. (Agree continuing w/ -preview9 seems better than going to `-previewA` or all the way to `-previewa`.)

@danroth27 what about the client-side Blazor packages in AspNetCore? (Again, I seem to remember @rynowak filing an issue about the overall naming but I don't recall where or the chosen branding.)

**Comment by danroth27** [comment]
@dougbu All of the Blazor WebAssembly packages need to continue to use the same preview branding.

**Comment by dougbu** [comment]
Found the issue: https://github.com/aspnet/AspNetCore/issues/13054

@JunTaoLuo let's leave 'release/3.0' alone in this repo. Could you look at continuing to use '-preview9' for the few AspNetCore projects mentioned in that issue? This needs to happen today or tomorrow I think (@Pilchie ?). Should be a small change in eng/Versions.props and the affected projects.

Do we need to do anything about -rc1 packages we may have published since https://github.com/aspnet/AspNetCore/pull/13341 went in?

**Pull request closed without merging**
