### PR TITLE
Move to bootstrap v4

### PR DESCRIPTION
**Pull request by FabriDamazio**
Move to Bootstrap to v4. Addresses #334 
Remove fonts folders because Bootstrap v4 doesn’t include an icon library by default.

### CODE REVIEW

**Comment by FabriDamazio** [comment]
@AWulkan you are right. I removed the  redundant MIME types. Tkx!

**Comment by Eilon** [comment]
@danroth27 - please note that if we take this, we need to update the ThirdPartyNotices.

**Comment by FabriDamazio** [comment]
@Eilon i can update the ThirdPartyNotices doc if you wish.

**Comment by Eilon** [comment]
@FabriDamazio you can give it a shot, but we'll need @danroth27 to review it 😄

**Comment by FabriDamazio** [comment]
@Eilon haha no problem with that! I'll do it.

**Comment by FabriDamazio** [comment]
@AWulkan changed `.flex-column` for ` .navbar-nav` as indicated in bootstrap docs.

@Eilon @danroth27 ThirdPartyNotices ready for review

**Comment by SteveSandersonMS** [comment]
@FabriDamazio Thanks so much for this!

The technical aspects of which files you've updated, code style, etc., all look perfect to me. I understand also it was necessary to drop the glyphicons.

The one bit I think could use a bit of further tweaking is the visual styling itself. Examples:

image
image

Rather than making small patches to the exact styling and positioning of elements within the existing structure, do you think we should consider changing a bit more radically?

It looks like the following is a more idiomatic dashboard style for Bootstrap 4: https://getbootstrap.com/docs/4.0/examples/dashboard/ To me it looks much cleaner and more modern than what we already have, with the exception of looking a bit colorless (which we could easily address by making the header bar some color other than gray).

@FabriDamazio If you're interested in switching the templates over to the Bootstrap 4-styled dashboard, that would be great. If not, no worries - we can take your PR here as a starting point and one of us would do the further style updates.

**Comment by FabriDamazio** [comment]
@SteveSandersonMS I agree with your points and I'll improve the templates styles following the given example and show the results in one day or two.

**Comment by danroth27** [comment]
@FabriDamazio Looks really nice! I know this is an asthetic comment, but personally I'd prefer something a bit more muted than the magenta coloring. To me red is pretty strongly associated with errors.

**Comment by FabriDamazio** [comment]
@danroth27 what about something like: 
image

**Comment by danroth27** [comment]
Maybe a teal green?

**Comment by FabriDamazio** [comment]
image

**Comment by danroth27** [comment]
@FabriDamazio That looks good to me.

**Comment by grahamehorner** [comment]
Q: should the templates/samples include the work that has been done on the site templates for constent/GDPR ? update is looking cool 😎

**Comment by FabriDamazio** [comment]
Bootstrap hamburger menu isnt working in v4 either. (see #329 ). 
If i add `jquery.min.js` and `bootstrap.min.js` and remove `bootstrap-native`, everything works. I tried many ways but i can manage it to work with bootstrap-native. Someone try make this works using bootstrap-native or should we drop bootstrap native and use jquery instead?

**Comment by SteveSandersonMS** [comment]
Thanks for trying. We definitely won’t add a jQuery dependency to the default template, but we could remove the hamburger button for now.

**Comment by FabriDamazio** [comment]
@SteveSandersonMS  OK, I'll remove the button and update the PR

**Comment by AWulkan** [comment]
@FabriDamazio Can it be because the JS script for bootstrap loads before the <app></app> content is loaded? Therefore it's not hooking up the html elements with event listeners correctly.

**Comment by FabriDamazio** [comment]
Visual updated to TEAL GREEN example. (Tkx @danroth27, nice color)

@SteveSandersonMS the hamburger button remain untouched (collapsed menu not working) We need more investigation about the causes. I understand we need use bootstrap-native due size and performance.

@AWulkan i tried that solutions but i think you are in the right way to solve it.

I can add icons after SVG support. Just tell me when.

**Comment by panesofglass** [comment]
This looks really nice! Out of curiosity, is there a reason to use bootstrap vs something like [bulma](https://bulma.io/), which doesn't include a JS library? Is bootstrap used b/c of popularity or to also show off JS interop? If the latter, are there any examples in the template showing interop? I don't recall seeing them, but it would be a nice way to show off interop and provide an additional reason for using bootstrap.

**Comment by AWulkan** [comment]
@panesofglass I think the only reason for using Bootstrap is because its popular. Bulma would be more optimal in terms of file size and lack of JS dependencies, but it is not as well known to people.

**Comment by SteveSandersonMS** [comment]
Thanks again @FabriDamazio!

In #619, parts of this PR were merged, along with some alternate styling work needed to account for mobile scenarios and make the hamburger menu work.

**Pull request closed without merging**
