### PR TITLE
Update branding to preview 4

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Part of https://github.com/aspnet/AspNetCore/pull/16829.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
@dougbu I'm curious why there's no DotNetFinalVersionKind specified in this repo. Without this, the final build will be 3.1.0 without any pre-release labels I believe.

**Comment by JunTaoLuo** [comment]
Ah nevermind, we just never set that value, so we always use the pre-release lable. No further changes needed then.

**Comment by JunTaoLuo** [comment]
FYI @wtgodbe for branding update post preview3

**Comment by JunTaoLuo** [comment]
@wtgodbe are these ready to go in yet?

**Comment by wtgodbe** [comment]
@JunTaoLuo I was planning on merging these with the stabilization PRs, which I'll merge after dependency flow hits each respective repo (stabilization PRs should be the last thing merged into each repo)

**Pull request merged**
