### PR TITLE
Fix for Dependency injection doesn't handle inheritance

### LINKED ISSUE #216: Dependency injection doesn't handle inheritance
Example scenario: if you subclass `Router`, e.g.,

    public class MyRouter : Router {}

... and then try to use `<MyRouter />`, it will fail because `Router` didn't get its `UriHelper` injected.

### PR DESCRIPTION
**Pull request by LunicLynx**
fix for #216

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks @LunicLynx! This is now merged. Great to get this fixed :)

**Comment by khellang** [comment]
Isn't this what `BindingFlags.FlattenHierarchy` does?

**Comment by SteveSandersonMS** [comment]
@khellang I thought so too, but it only applies to `public` members. We want to include `private` and `protected` too.

**Comment by khellang** [comment]
Ah. Well, it includes `protected`, but not private (from base class):

```csharp
using System;
using System.Reflection;

public class A
{
	public int PublicA { get; set; }

	protected int ProtectedA { get; set; }
	
	internal int InternalA { get; set; }

	private int PrivateA { get; set; }
}

public class B : A
{
	public int PublicB { get; set; }

	protected int ProtectedB { get; set; }
	
	internal int InternalB { get; set; }

	private int PrivateB { get; set; }
}
					
public class Program
{
	public static void Main()
	{
		const BindingFlags flags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.FlattenHierarchy;
		
		foreach (var property in typeof(B).GetProperties(flags))
		{
			Console.WriteLine(property.Name);	
		}
	}
}
```

Outputs:

```
PublicB
ProtectedB
InternalB
PrivateB
PublicA
ProtectedA
InternalA
```

Runnable example: https://dotnetfiddle.net/12Fg1k

**Comment by LunicLynx** [comment]
@khellang I had the same idea. But as @SteveSandersonMS says that does not work.

I think that this isn't easily supported seems like an oversight in the api. Doing it this way returns the public properties several times, which is why the must be filtered with `.Where(prop => prop.ReflectedType == prop.DeclaringType)`. 

It would be nice to have a method `GetDeclaredProperties` with `BindingFlags`.

**Comment by khellang** [comment]
There's also `typeof(Blah).GetTypeInfo().GetRuntimeProperties()`, which seems to return the same results 😄

**Comment by SteveSandersonMS** [comment]
Yes, the docs for that seem wrong or at least very misleading:

> This method returns all properties defined on the specified type, including **inherited, non-public**, instance, and static properties - https://msdn.microsoft.com/en-us/library/system.reflection.runtimereflectionextensions.getruntimeproperties(v=vs.110).aspx

It returns properties that are inherited, and ones that are non-public, but **not** ones that are both inherited *and* nonpublic.

**Pull request merged**
