### PR TITLE
Removed trailing space from template survey link

### PR DESCRIPTION
**Pull request by jnm2**
Before:

After:

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion, @jnm2!

I don't think we'd want to add the comment tag there in the template, as it will confuse people. Especially those less familiar with the technology.

I would prefer the solution of putting the whole `<a>` tag on a single line (even though it will be a long line). @jnm2, are you interested in changing it that way?

**Comment by jnm2** [comment]
@SteveSandersonMS Absolutely, no problem!

**Comment by SteveSandersonMS** [comment]
Thanks @jnm2! It's merged.

**Comment by jnm2** [comment]
Thank you!

**Pull request merged**
