### PR TITLE
Scan only declared methods for JS interop

### LINKED ISSUE #1295: Getting erro calling registered JSInvokable function in component lib
I have a Component lib created using the blazom component lib template (CLI) asn have registered a instance method to be invokable in th JS side

```
[JSInvokable]
public Task ClearSelection()
{
...
}
```

But when calling it i get the following error:

```
Error: System.InvalidOperationException: The assembly 'RPedretti.Blazor.Components' contains more than one [JSInvokable] method with identifier 'ClearSelection'. All [JSInvokable] methods within the same assembly must have different identifiers. You can pass a custom identifier as a parameter to the [JSInvokable] attribute.
```

I tried to to register using a identifyer but the error remains. This doesn't happens in a instance method registered in the main assembly

### PR DESCRIPTION
**Pull request by danroth27**
Fixes #1295

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
The implementation looks great - thanks @danroth27!

Would it be possible also to have a test to show what behavior has changed? There are some existing tests for `[JSInvokable]` discovery in `DotNetDispatcherTest.cs` in `Microsoft.JSInterop.Test`, so it could be added there.

**Comment by danroth27** [comment]
Looks like there was also a test failure on AppVeyor. I'm not sure if it's related to this change:

```
  Failed   Microsoft.AspNetCore.Blazor.E2ETest.ServerExecutionTests.ServerComponentRenderingTest.CanTriggerAsyncEventHandlers
5027
  Error Message:
5028
   Assert.Equal() Failure
5029
  Expected: Stopped
5030
  Actual:   Started
5031
  Stack Trace:
5032
     at Microsoft.AspNetCore.Blazor.E2ETest.Infrastructure.WaitAssert.WaitAssertCore(Action assertion, TimeSpan timeout) in /_/test/Microsoft.AspNetCore.Blazor.E2ETest/Infrastructure/WaitAssert.cs:line 69
5033
     at Microsoft.AspNetCore.Blazor.E2ETest.Infrastructure.WaitAssert.Equal[T](T expected, Func`1 actual) in /_/test/Microsoft.AspNetCore.Blazor.E2ETest/Infrastructure/WaitAssert.cs:line 21
5034
  Standard Output Messages:
5035
   browser Logs from Selenium:
5036
   [8/16/2018 3:58:23 AM] - Info - http://127.0.0.1:51527/subdir/_framework/blazor.server.js 15:6945 "Information: Normalizing '_blazor' to 'http://127.0.0.1:51527/subdir/_blazor'."
5037
   [8/16/2018 3:58:23 AM] - Info - http://127.0.0.1:51527/subdir/_framework/blazor.server.js 15:6945 "Information: WebSocket connected to ws://127.0.0.1:51527/subdir/_blazor?id=Z8r5Fx8X08dHxNvKXh5EnQ"
5038
   [8/16/2018 3:58:23 AM] - Info - http://127.0.0.1:51527/subdir/_framework/blazor.server.js 15:6945 "Information: Using HubProtocol 'messagepack'."
5039
   
5040
   
5041
   server Logs from Selenium:
5042
   
5043
   
5044
   driver Logs from Selenium:
5045
   
5046
   
5047
  
5048
  
5049
  [xUnit.net 00:01:36.2018497]     Microsoft.AspNetCore.Blazor.E2ETest.ServerExecutionTests.ServerComponentRenderingTest.CanTriggerAsyncEventHandlers [FAIL]
```

**Comment by danroth27** [comment]
:up::date: Added test

**Comment by SteveSandersonMS** [comment]
Looks perfect - thanks @danroth27! Merged.

**Pull request merged**
