### PR TITLE
Components with children

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Work in progress

### CODE REVIEW

**Comment by muqeet-khan** [comment]
In current implementation, I can do this in Home.cshtml to include a component from Shared:

`    <c:Shared.Header />`

However, I need to include the Full type name. Could you consider including `using Shared` when adding components so that anything in shared can be included in components in Pages by default?

**Comment by SteveSandersonMS** [comment]
> However, I need to include the Full type name. Could you consider including using Shared when adding components so that anything in shared can be included in components in Pages by default?

That is already implemented. You can write:

    @using Shared
    <c:Header />

**Comment by muqeet-khan** [comment]
Oh! I had tried that, then backed away because VS was showing it as an error. 

image

**Comment by SteveSandersonMS** [comment]
Then your namespace probably isn't just `Shared`. Do you need to write something like `using StandaloneApp.Shared` instead?

**Pull request merged**
