### PR TITLE
Looks like adding a second solution broke our CIs

### PR DESCRIPTION
**Pull request by rynowak**

### CODE REVIEW

**Comment by rynowak** [comment]
Actually - were these ever working? I assumed that I broke things...

**Comment by SteveSandersonMS** [comment]
CI hasn't been set up yet. We still need to add AppVeyor/Travis configs. https://github.com/aspnet/Blazor/issues/8

**Comment by SteveSandersonMS** [comment]
Oh, wait, that's what you're doing in this PR. I'll investigate what else needs to be configured.

**Comment by SteveSandersonMS** [comment]
Merged, along with some other updates to make it build with .NET Core, run the Selenium tests, etc.

**Comment by rynowak** [comment]
Yeah if you were able to get this working then cool beans 👍 I don't have a lot of knowledge about how/why we set up things the way we did for the ASP.NET repos, but I know how to CTRL+C CTRL+V

**Pull request closed without merging**
