### PR TITLE
Don't ship blazor packages from release/3.1

### PR DESCRIPTION
**Pull request by wtgodbe**
@javiercn @pranavkm @JunTaoLuo @mkArtakMSFT PTAL

### CODE REVIEW

**Comment by javiercn** [comment]
@wtgodbe Just to confirm, we already removed the artifacts from 3.1 GA, didn't we?

**Comment by wtgodbe** [comment]
> Just to confirm, we already removed the artifacts from 3.1 GA, didn't we?

It looks like we still have `Microsoft.AspNetCore.Blazor.Mono.3.1.0-preview4.19562.1` in the drop - should it be removed?

**Comment by danroth27** [comment]
> It looks like we still have Microsoft.AspNetCore.Blazor.Mono.3.1.0-preview4.19562.1 in the drop - should it be removed?

Yes.

**Comment by wtgodbe** [comment]
There's a number of other `preview4` Blazor packages ready to ship with GA, such as `Microsoft.AspNetCore.Blazor.3.1.0-preview4.19566.1` from AspNetCore. Should those be removed as well?

**Comment by danroth27** [comment]
@wtgodbe Yup, pretty much anything with "Blazor", "Blazor.Mono", or "Mono.WebAssembly" in its name should not ship as part of the GA release. Instead we will be shipping those packages separately.

**Comment by danroth27** [comment]
@wtgodbe Also Microsoft.JSInterop.

**Comment by wtgodbe** [comment]
Done

**Pull request merged**
