### PR TITLE
Add support for binding decimal? double? float? long? int? bool?

### PR DESCRIPTION
**Pull request by IvanJosipovic**
Resolves Issue #1007

### CODE REVIEW

**Comment by vertonghenb** [comment]
@IvanJosipovic , nice!

**Comment by Andrzej-W** [comment]
Thank you very much. Hopefully it will merged before 0.7 release.

**Comment by akorchev** [comment]
Should this support `DateTime?` as well?

**Comment by SteveSandersonMS** [comment]
Thanks for this! It's now moved to https://github.com/aspnet/AspNetCore/pull/4600

**Pull request closed without merging**
