### PR TITLE
fix #396

### LINKED ISSUE #396: Timespan doesn't deserialize correctly in GetJsonAsync
Using the extension method `Microsoft.AspNetCore.Blazor.HttpClientJsonExtensions.GetJsonAsync` seems to have issues deserializing timespans.

Server code (asp.net core):

    [HttpGet("[action]")]
    public Event Event()
    {
        return new Event
        {
            StartTime = DateTime.Parse("2018-03-27 10:00"),
            Length = TimeSpan.FromHours(3)
        };
    }

Client code (blazor page):

    protected override async Task OnInitAsync()
    {
        var date = await Http.GetJsonAsync<Event>("api/SampleData/Event");
    }

The JSON sent:

    {"Length":"03:00:00","StartTime":"2018-03-27T10:00:00"}

And the exception received:

```
WASM: [System.InvalidCastException] Invalid cast from 'System.String' to 'System.TimeSpan'.
MonoPlatform.ts:169:28
WASM:   at System.Convert.DefaultToType (System.IConvertible value, System.Type targetType, System.IFormatProvider provider) <0x19bd598 + 0x003c2> in <511bb7d2e8e340dcbd00380e5e48092a>:0 
MonoPlatform.ts:169:28
WASM:   at System.String.System.IConvertible.ToType (System.Type type, System.IFormatProvider provider) <0x19bd550 + 0x00018> in <511bb7d2e8e340dcbd00380e5e48092a>:0 
MonoPlatform.ts:169:28
WASM:   at System.Convert.ChangeType (System.Object value, System.Type conversionType, System.IFormatProvider provider) <0x1984220 + 0x0036e> in <511bb7d2e8e340dcbd00380e5e48092a>:0 
MonoPlatform.ts:169:28
WASM:   at SimpleJson.PocoJsonSerializerStrategy.DeserializeObject (System.Object value, System.Type type) <0x175e058 + 0x002b4> in <6f55c2fa30114054ab77a67cb3b359ec>:0 
MonoPlatform.ts:169:28
WASM:   at SimpleJson.PocoJsonSerializerStrategy.DeserializeObject (System.Object value, System.Type type) <0x175e058 + 0x0073a> in <6f55c2fa30114054ab77a67cb3b359ec>:0 
MonoPlatform.ts:169:28
WASM:   at SimpleJson.SimpleJson.DeserializeObject (System.String json, System.Type type, SimpleJson.IJsonSerializerStrategy jsonSerializerStrategy) <0x174c9e8 + 0x00066> in <6f55c2fa30114054ab77a67cb3b359ec>:0 
MonoPlatform.ts:169:28
WASM:   at SimpleJson.SimpleJson.DeserializeObject[T] (System.String json) <0x19b9d60 + 0x0001a> in <6f55c2fa30114054ab77a67cb3b359ec>:0 
MonoPlatform.ts:169:28
WASM:   at Microsoft.AspNetCore.Blazor.JsonUtil.Deserialize[T] (System.String json) <0x19b9d28 + 0x00008> in <6f55c2fa30114054ab77a67cb3b359ec>:0 
MonoPlatform.ts:169:28
WASM:   at Microsoft.AspNetCore.Blazor.HttpClientJsonExtensions+<GetJsonAsync>d__0`1[T].MoveNext () <0x16b6e18 + 0x000c4> in <6f55c2fa30114054ab77a67cb3b359ec>:0 
MonoPlatform.ts:169:28
WASM: --- End of stack trace from previous location where exception was thrown ---
MonoPlatform.ts:169:28
WASM:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x19c2888 + 0x00082> in <511bb7d2e8e340dcbd00380e5e48092a>:0 
MonoPlatform.ts:169:28
WASM:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x19be888 + 0x00066> in <511bb7d2e8e340dcbd00380e5e48092a>:0 
MonoPlatform.ts:169:28
WASM:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x19a1620 + 0x00018> in <511bb7d2e8e340dcbd00380e5e48092a>:0 
MonoPlatform.ts:169:28
WASM:   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x19be648 + 0x0000c> in <511bb7d2e8e340dcbd00380e5e48092a>:0 
MonoPlatform.ts:169:28
WASM:   at Blazor.Client.Pages.Calendar+<OnInitAsync>d__2.MoveNext () <0x16b0498 + 0x000d0> in <b1a2e7c990da409c91a20c367fe367d1>:0 
MonoPlatform.ts:169:28
```

Note that the page works fine with just datetimes (and for this case a workaround would be to send the start and end date instead of the length). However one would expect that since the server handles timespans perfectly fine and since the client handles datetimes perfectly fine that the client would also handle timespans.

I realize that ultimately this is likely a SimpleJson issue, but since this extension method is likely to be pretty heavily used it's important IMO for it to work for the commonly used core .NET types. 

EDIT: After digging a bit it looks like the SimpleJson also didn't support DateTime or DateTimeOffset and this support was added to this repo's fork of it.

### PR DESCRIPTION
**Pull request by bdparrish**
added TimeSpan serialization and deserialization using ISO 8601 (https://en.wikipedia.org/wiki/ISO_8601#Durations)

### CODE REVIEW

**Comment by bdparrish** [comment]
There was no real discussion on which way the conversion was intended to be processed, so I was using the best standard that would make sense, hence the ISO 8601 format.  If it makes more sense for a standard `.ToString()`, then that is easily doable.

**Comment by grahamehorner** [comment]
@bdparrish TBH IMHO it seem wrong for a json serialization to have a dependency on xml and I would have opted for the ((TimeSpan)input).ToString("c")

**Comment by bdparrish** [comment]
`((TimeSpan)input).ToString("c")` produces a string that cannot be used with a TimeSpan constructor.  Am I missing a constructor overload somewhere that takes a string?

The `System.Xml` library is a built in .NET library and reduces the code necessary, so it all looked cleaner IMO.  I am happy to change to the `.ToString("c")` and add the necessary parsing for the deserialization steps.

**Comment by tdinucci** [comment]
@bdparrish You can use TimeSpan.Parse(...) for this

I'm obviously not on the team so I'd wait to hear back from someone official before you change things.  However this is the default format used with the JSON serialisers I've come across in the past.

**Comment by bdparrish** [comment]
@tdinucci - shoot man, i am just trying to help.  not on the team either.  I'll go with the `TryParse()`.

**Comment by SteveSandersonMS** [comment]
Thanks @bdparrish - this looks perfect! I'm glad you avoided the `System.Xml` dependency in the end.

It's now merged.

**Pull request closed without merging**
